export const PROJECTS = [
  {
    id: "31few3f4ew546e5t",
    title: "Reddit Clone",
    role: "Front End Development",
    image: "/assets/icons/reddit.svg",
    tasks: [
      {
        id: 1,
        name: "Planning Project",
        rounds: 10,
        completed: 8,
        status: "done",
      },
      {
        id: 2,
        name: "Get Business logic",
        rounds: 12,
        completed: 12,
        status: "done",
      },
      {
        id: 3,
        name: "Get project resources & assets",
        rounds: 10,
        completed: 10,
        status: "done",
      },
      {
        id: 4,
        name: "Setup Database and Schema",
        rounds: 8,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 4,
        status: "pending",
      },
      {
        id: 6,
        name: "Develop Front End",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 13,
        completed: 0,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 10,
        completed: 0,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 14,
        completed: 0,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 6,
        completed: 0,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 0,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/20.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/33.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/26.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/24.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/34.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/3.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/5.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/17.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
      },
    ],
  },
  {
    id: "shgrsehrfg45t",
    title: "FaceBook Clone",
    role: "Front End",
    image: "/assets/icons/facebook.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 4,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 10,
        completed: 10,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 8,
        completed: 8,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 11,
        completed: 11,
        status: "done",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 5,
        completed: 5,
        status: "done",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 3,
        completed: 3,
        status: "done",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 6,
        completed: 2,
        status: "pending",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 9,
        completed: 4,
        status: "pending",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 5,
        completed: 1,
        status: "pending",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 7,
        completed: 0,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 14,
        completed: 0,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/44.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/2.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/3.jpg",
      },
    ],
  },
  {
    id: "gda97465d4g8s6rg47",
    title: "Figma Clone",
    role: "Front End ",
    image: "/assets/icons/figma.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 7,
        completed: 7,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 10,
        completed: 10,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 3,
        completed: 3,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 13,
        completed: 10,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 8,
        completed: 5,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 5,
        completed: 3,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 12,
        completed: 8,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 20,
        completed: 0,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 0,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 15,
        completed: 0,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 11,
        completed: 0,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 19,
        completed: 0,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/21.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/32.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/52.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/68.jpg",
      },
    ],
  },
  {
    id: "arwgw4retya435q",
    title: "Social App",
    role: "Full Stack ",
    image: "/assets/icons/pinterest.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 21,
        completed: 21,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 10,
        completed: 10,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 5,
        completed: 5,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 15,
        completed: 15,
        status: "done",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 21,
        completed: 21,
        status: "done",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 13,
        completed: 13,
        status: "done",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 23,
        completed: 23,
        status: "done",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 8,
        completed: 8,
        status: "done",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 14,
        completed: 14,
        status: "done",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 7,
        completed: 2,
        status: "pending",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/36.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/9.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/7.jpg",
      },
    ],
  },
  {
    id: "agtreh544regqreh8t4e8h",
    title: "Youtube Clone",
    role: "Back End",
    image: "/assets/icons/youtube.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 4,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 18,
        completed: 18,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 20,
        completed: 20,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 14,
        completed: 12,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 10,
        completed: 7,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 16,
        completed: 12,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 6,
        completed: 3,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/12.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/15.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/64.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
      },
    ],
  },
  {
    id: "ey5thhaok0nksf-j",
    title: "DropBox",
    role: "Front End",
    image: "/assets/icons/dropbox.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/67.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/68.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/18.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/48.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/68.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/28.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/60.jpg",
      },
    ],
  },
  {
    id: "sdvafedddafgrgr",
    title: "New Project",
    role: "Front End Development",
    image: "/assets/icons/pinterest.svg",

    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/30.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/33.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/26.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/24.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/34.jpg",
      },
    ],
  },
  {
    id: "bshkiyhshrthrtsst",
    title: "Reddit Clone",
    role: "Front End",
    image: "/assets/icons/reddit.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/64.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/47.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/20.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/3.jpg",
      },
    ],
  },
  {
    id: "sthtsrhthtrtshsht",
    title: "Figma Clone",
    role: "Front End ",
    image: "/assets/icons/reddit.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/24.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/22.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/42.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/78.jpg",
      },
    ],
  },
  {
    id: "bfdshththaqththsht",
    title: "Social App",
    role: "Full Stack ",
    image: "/assets/icons/reddit.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/16.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/29.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/7.jpg",
      },
    ],
  },
  {
    id: "htshththshfdsdgfdsh",
    title: "Youtube Clone",
    role: "Back End",
    image: "/assets/icons/reddit.svg",
    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/12.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/15.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/64.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/6.jpg",
      },
    ],
  },
  {
    id: "shshtshthrterretre",
    title: "DropBox",
    role: "Front End",
    image: "/assets/icons/reddit.svg",

    tasks: [
      {
        id: 1,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 2,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 3,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 4,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "pending",
      },
      {
        id: 5,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 6,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 7,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "done",
      },
      {
        id: 8,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 9,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 10,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 11,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
      {
        id: 12,
        name: "Wireframing & Designing the UI",
        rounds: 4,
        completed: 2,
        status: "on hold",
      },
    ],
    users: [
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/67.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/68.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/18.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/48.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/men/68.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/28.jpg",
      },
      {
        name: "John Doe",
        email: "john.doe@example.com",
        image: "https://randomuser.me/api/portraits/women/60.jpg",
      },
    ],
  },
];
